### PR TITLE
init_project

### PR DESCRIPTION
**Pull request by giangkute99**

### CODE REVIEW

**Comment by giangkute99** [comment]
ready

**Comment by longcn-1045** [comment]
fix comment theo pull này bạn nhé
https://github.com/dungdnv-1036/sample_app/pull/1

**Comment by longcn-1045** [comment]
cmt

**Review by longcn-1045 — COMMENTED** [review]
comment

**Comment by giangkute99** [comment]
ready

**Comment by giangkute99** [comment]
ready

**Comment by ngocvt-0484** [comment]
merged

**Pull request merged**
